# Generated by Django 6.0.3 on 2026-03-03 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='external_cover_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='track',
            name='source_type',
            field=models.CharField(choices=[('UPLOAD', 'Upload'), ('YOUTUBE', 'YouTube')], default='UPLOAD', max_length=12),
        ),
        migrations.AddField(
            model_name='track',
            name='youtube_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='audio/'),
        ),
    ]
