# Generated by Django 6.0.3 on 2026-03-03 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0002_track_external_cover_url_track_source_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='youtube_id',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='youtube_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
