# Generated by Django 6.0.3 on 2026-03-03 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0003_track_youtube_id_alter_track_youtube_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
